version: '3.7'
services:

  phpserver1:
    build: .
    container_name: 'server1'
    volumes:
      - ./public-html:/var/www/html
      - ./20_xdebug_setting.ini:/usr/local/etc/php/conf.d/20_xdebug_setting.ini
    environment:
      TEST: "test"
    ports: 
      - "80:80"
    expose: 
      - "80"

